// Premium, high-converting service content for Virtuo Edge
// This file contains professional copywriting for all 15 services

export const premiumServices = [
  {
    title: "Website Development",
    slug: "website-development",
    description: "Fast, conversion-optimized websites that rank on Google and turn visitors into customers.",
    longDescription: "Virtuo Edge builds high-performance websites designed to convert. We combine cutting-edge technology with proven UX principles to create sites that rank, load fast, and generate leads 24/7. Perfect for startups scaling their online presence.",
    pricing: "Custom quote",
    pricingRange: "$1000 - $3500+",
    pricingDetails: "Starter: $1000 (5-page site). Growth: $1800–$3500+ (e-commerce, CMS, advanced integrations).",
    features: [
      "Mobile-first, responsive design for all devices",
      "SEO-optimized architecture and fast loading speed",
      "Conversion-focused UX and checkout optimization",
      "CMS integration for easy content management",
      "Third-party API integrations and payment gateways",
    ],
    benefits: [
      "SEO-friendly sites that rank higher on Google",
      "Mobile visitors convert at higher rates",
      "Reduce bounce rate and increase time on site",
      "Update content yourself without technical help",
    ],
  },
  {
    title: "AI Automation Setup",
    slug: "ai-automation-setup",
    description: "Automate repetitive tasks and save your team 20+ hours every week with intelligent workflows.",
    longDescription: "Virtuo Edge's AI automation cuts manual work by up to 70%. We design custom workflows that handle data entry, lead nurturing, reporting, and communication—24/7. Perfect for scaling without hiring. Most startups see ROI within 2–4 weeks.",
    pricing: "Custom quote",
    pricingRange: "$1000 - $2500",
    pricingDetails: "Basic: $1000 (1–2 workflows). Advanced: $1500–$2500 (complex lead funnels, multi-step automation).",
    features: [
      "Custom workflow design matching your exact process",
      "Lead generation and nurturing automation",
      "Automated email and SMS campaigns",
      "Real-time data sync between CRM and apps",
      "Intelligent routing and conditional logic",
    ],
    benefits: [
      "Reduce manual work by up to 70%",
      "Eliminate human error in data handling",
      "Scale operations without hiring",
      "Fast setup: live in 3–5 days",
    ],
  },
  {
    title: "AI Chatbot Integration",
    slug: "ai-chatbot-integration",
    description: "Smart AI chatbots that answer instantly, qualify leads, and never miss a customer inquiry.",
    longDescription: "Virtuo Edge's AI chatbots work 24/7 across your website, WhatsApp, and social media. They understand context, answer questions, and capture lead details automatically—so your team only talks to hot prospects. Results: 40–60% higher lead quality.",
    pricing: "Custom quote",
    pricingRange: "$1000 - $1800",
    pricingDetails: "Starter: $1000 (FAQ integration). Pro: $1200–$1800 (trained chatbot with lead qualification).",
    features: [
      "Multi-channel deployment (web, WhatsApp, Messenger)",
      "Natural language understanding with AI training",
      "Automatic lead capture and CRM sync",
      "Conversation analytics and insights",
      "Multi-language support",
    ],
    benefits: [
      "Answer customers instantly, 24/7",
      "Qualify and capture leads automatically",
      "Reduce support team workload by 50%+",
      "Higher lead conversion rates",
    ],
  },
  {
    title: "Full Brand Creation",
    slug: "full-brand-creation",
    description: "Complete brand identity that makes customers trust you instantly and remember you forever.",
    longDescription: "Virtuo Edge creates standout brand identities from scratch. Logo, color palette, typography, brand voice, messaging framework—everything. We ensure consistency across all touchpoints so customers recognize and trust your brand immediately.",
    pricing: "Custom quote",
    pricingRange: "$2500 - $4500",
    pricingDetails: "Includes logo design, brand guidelines, visual system, tone of voice, and 10 social assets.",
    features: [
      "Custom logo design with multiple concepts",
      "Complete brand guidelines document",
      "Color palette and typography system",
      "Brand voice and messaging framework",
      "Social media and web asset pack",
    ],
    benefits: [
      "Stand out from competitors instantly",
      "Consistent identity across all channels",
      "Professional brand builds customer trust",
      "Ready-to-use assets for immediate launch",
    ],
  },
  {
    title: "Motion Graphics",
    slug: "motion-graphics",
    description: "Stop-the-scroll animations that explain your product in seconds and boost engagement.",
    longDescription: "Virtuo Edge's motion graphics turn complex ideas into engaging videos. From explainer animations to social media clips and product demos, we create premium content that converts. Average engagement boost: 3–4x higher than static content.",
    pricing: "Per asset",
    pricingRange: "$400 - $1200 per asset",
    pricingDetails: "Explainer video: $500–$1000. Promo animation: $400–$700. Custom 3D motion: $800–$1200.",
    features: [
      "2D and 3D animation with custom style",
      "Explainer video production and voiceover",
      "Logo animation and brand motion guidelines",
      "Social media-ready video exports",
      "Product demo and feature showcase videos",
    ],
    benefits: [
      "Engage viewers faster with dynamic motion",
      "Explain complex features simply",
      "Higher social media engagement and shares",
      "Multiple export formats for any platform",
    ],
  },
  {
    title: "Video Editing (Short Content/Reels)",
    slug: "video-editing-short",
    description: "Viral-ready Reels and TikToks edited monthly with trending effects and scroll-stopping hooks.",
    longDescription: "Virtuo Edge turns raw footage into platform-optimized short content. We handle editing, effects, captions, and audio—so you focus on growth. Monthly package includes 10–20 high-quality Reels, Shorts, or TikToks delivered on schedule.",
    pricing: "Monthly retainer",
    pricingRange: "$800 - $1500/month",
    pricingDetails: "10–20 videos monthly, including color grading, captions, trending effects, and custom music.",
    features: [
      "Professional cutting and transitions",
      "Color grading and visual consistency",
      "Automated captions and text overlays",
      "Trending effects and sound design",
      "Platform-optimized for Instagram, TikTok, YouTube",
    ],
    benefits: [
      "Consistent content output, no production stress",
      "Optimized for maximum reach and engagement",
      "Save 10–15 hours monthly on editing",
      "Trending audio and effects included",
    ],
  },
  {
    title: "Video Editing (Long Content)",
    slug: "video-editing-long",
    description: "YouTube-ready videos edited monthly: podcasts, tutorials, vlogs with professional polish.",
    longDescription: "Virtuo Edge handles full post-production for long-form content. We edit, color grade, design graphics, and optimize for YouTube—so you upload polished videos on schedule. Perfect for creators scaling their channel.",
    pricing: "Monthly retainer",
    pricingRange: "$1200 - $2500/month",
    pricingDetails: "4–8 long-form videos monthly (10–30 min), including color grade, graphics, and YouTube optimization.",
    features: [
      "Multi-camera editing with seamless cuts",
      "Advanced color grading and correction",
      "Motion graphics, titles, and lower-thirds design",
      "Professional audio mixing and music sync",
      "Chapter markers and YouTube SEO optimization",
    ],
    benefits: [
      "Professional production quality every video",
      "More time creating, less time editing",
      "Higher viewer retention and watch time",
      "Consistent upload schedule maintained",
    ],
  },
  {
    title: "Monthly AI Automation Maintenance",
    slug: "ai-automation-maintenance",
    description: "24/7 monitoring and optimization keeps your automation running flawlessly and profitable.",
    longDescription: "Virtuo Edge maintains your automation systems like a dedicated team member. We monitor performance, fix issues proactively, optimize workflows, and ensure zero downtime. Peace of mind plus continuous improvement.",
    pricing: "Monthly retainer",
    pricingRange: "$400 - $700/month",
    pricingDetails: "Includes 24/7 monitoring, bug fixes, performance tuning, and monthly optimization report.",
    features: [
      "24/7 system monitoring and alerts",
      "Proactive issue detection and resolution",
      "Monthly workflow optimization and tuning",
      "Performance reports and ROI tracking",
      "Priority support and emergency fixes",
    ],
    benefits: [
      "Zero downtime and uninterrupted automation",
      "Continuous performance improvements",
      "Maximize ROI from existing automation",
      "Expert support when you need it",
    ],
  },
  {
    title: "SEO Optimization & Strategy",
    slug: "seo-optimization",
    description: "Rank on Google and drive qualified organic traffic that converts to customers.",
    longDescription: "Virtuo Edge's SEO strategy combines technical optimization, content strategy, and link building. We focus on keywords with buying intent so you attract prospects ready to buy. Results: 200–300% traffic increase within 6 months for most clients.",
    pricing: "Monthly retainer",
    pricingRange: "$700 - $1500/month",
    pricingDetails: "Technical SEO, keyword strategy, on-page optimization, content creation, and monthly reporting.",
    features: [
      "Technical SEO audit and implementation",
      "Keyword research targeting buying intent",
      "On-page content optimization",
      "Link building and outreach campaigns",
      "Monthly ranking and traffic reports",
    ],
    benefits: [
      "Rank on page one for target keywords",
      "Organic traffic increases 200–300%",
      "Long-term ROI that compounds monthly",
      "Reduce reliance on paid ads",
    ],
  },
  {
    title: "Social Media Ads Management",
    slug: "social-media-ads",
    description: "Profitable ad campaigns on Facebook, Instagram, and TikTok with consistent ROAS.",
    longDescription: "Virtuo Edge manages your entire paid social strategy: audience targeting, creative testing, bid optimization, and scaling. We focus on measurable conversions, not just clicks. Average client sees 2.5–4x ROAS within first 60 days.",
    pricing: "Monthly retainer (ad spend separate)",
    pricingRange: "$800 - $1500/month",
    pricingDetails: "Campaign strategy, creative design, A/B testing, optimization, and daily monitoring. Ad spend budgeted separately.",
    features: [
      "Multi-platform campaign strategy and setup",
      "Custom audience targeting and segmentation",
      "Creative design and A/B testing",
      "Daily bid optimization and scaling",
      "Conversion tracking and analytics",
    ],
    benefits: [
      "Lower cost per acquisition",
      "Higher conversion rates through targeting",
      "Daily optimization maximizes ROI",
      "Professional creatives that convert",
    ],
  },
  {
    title: "Graphic Design",
    slug: "graphic-design",
    description: "On-brand visuals for social media, ads, and websites that look expensive and convert.",
    longDescription: "Virtuo Edge creates consistent, high-quality graphics that strengthen your brand. From social posts to ad banners, email headers to infographics—we maintain visual consistency that builds recognition and trust with your audience.",
    pricing: "Monthly retainer",
    pricingRange: "$600 - $1000/month",
    pricingDetails: "Unlimited revisions on social posts, ads, email templates, and web graphics each month.",
    features: [
      "Social media post templates and designs",
      "Ad banners and display creative",
      "Email headers and newsletter designs",
      "Infographics and data visualizations",
      "Print-ready designs (brochures, flyers)",
    ],
    benefits: [
      "Consistent visual branding everywhere",
      "Professional look builds credibility",
      "Fast turnaround on new designs",
      "Unlimited revisions until perfect",
    ],
  },
  {
    title: "Monthly Website Maintenance",
    slug: "website-maintenance",
    description: "Keep your website secure, fast, and always online with expert monthly care.",
    longDescription: "Virtuo Edge handles all technical website maintenance: security updates, performance optimization, backups, and monitoring. Your site stays secure, fast, and available 24/7 so you can focus on business growth.",
    pricing: "Monthly retainer",
    pricingRange: "$350 - $600/month",
    pricingDetails: "Includes security monitoring, daily backups, updates, performance optimization, and priority support.",
    features: [
      "Daily automated backups and recovery",
      "Security monitoring and threat prevention",
      "Performance optimization and speed tuning",
      "Plugin and software updates",
      "Uptime monitoring and alerts",
    ],
    benefits: [
      "Always secure against threats",
      "Optimal loading speed maintained",
      "Quick issue resolution",
      "Zero downtime and data loss protection",
    ],
  },
  {
    title: "3D Modeling & Visualization",
    slug: "3d-modeling",
    description: "Photorealistic 3D renders that impress clients and boost product sales.",
    longDescription: "Virtuo Edge creates photorealistic 3D models and animations. From product visualization to architectural renderings and AR experiences, we help you showcase ideas before they're built. Clients report 30–50% higher engagement with 3D content.",
    pricing: "Per project",
    pricingRange: "$300 - $1500",
    pricingDetails: "Product renders: $300–$800. Architectural: $600–$1200. AR/VR: $1000–$1500.",
    features: [
      "Product 3D modeling and photorealistic rendering",
      "Architectural visualization and walkthroughs",
      "AR and VR experience creation",
      "Character and asset design",
      "Animation and motion graphics",
    ],
    benefits: [
      "Visualize products before manufacturing",
      "Impress clients with premium renders",
      "Reduce photography and prototype costs",
      "Stand out with immersive 3D experiences",
    ],
  },
  {
    title: "API Integration & Development",
    slug: "api-integration",
    description: "Custom APIs and integrations that connect your entire tech stack seamlessly.",
    longDescription: "Virtuo Edge builds and integrates APIs to make your apps and services work together. From payment gateways to CRM syncing to custom data flows, we eliminate manual work and create scalable connections between all your tools.",
    pricing: "Project-based",
    pricingRange: "$800 - $2500",
    pricingDetails: "Simple integration: $800–$1200. Custom API: $1200–$2000. Complex multi-system: $2000–$2500.",
    features: [
      "Custom REST and GraphQL API development",
      "Third-party API integration (Stripe, HubSpot, etc.)",
      "Real-time data synchronization",
      "Webhook implementation and monitoring",
      "Full API documentation and testing",
    ],
    benefits: [
      "Seamless data flow between all systems",
      "Eliminate manual data entry and errors",
      "Enable powerful integrations",
      "Scalable architecture for growth",
    ],
  },
  {
    title: "Custom Software Solutions",
    slug: "custom-software",
    description: "Bespoke web apps and dashboards built exactly for your business and goals.",
    longDescription: "Virtuo Edge develops custom software tailored to your exact needs. Whether it's an internal dashboard, client portal, or SaaS tool, we build scalable, secure software designed for your success. Full ownership, no licensing fees.",
    pricing: "Project-based",
    pricingRange: "$2000 - $5000+",
    pricingDetails: "Internal tools: $2000–$3000. Custom apps: $3000–$5000. Enterprise: custom quote.",
    features: [
      "Custom web application development",
      "Admin dashboards and client portals",
      "Database design and optimization",
      "User authentication and security",
      "Cloud deployment and scaling",
    ],
    benefits: [
      "Software built for your unique needs",
      "Full control and ownership",
      "Scalable as your business grows",
      "Dedicated support and maintenance",
    ],
  },
];
